workflows:
  ios:
    name: Flutter iOS Workflow
    max_build_duration: 60
    instance_type: macos-latest
    build:
      scripts:
        - flutter pub get
        - flutter build ios --release
    artifacts:
      - build/ios/iphoneos/Runner.app
