name: midi_visualizer
description: A simple MIDI velocity visualizer for 88-key piano
version: 1.0.0

environment:
  sdk: '^3.7.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_midi_command: ^0.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
